---
output:
  pdf_document: 
    fig_height: 4
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(cowplot)
library(magick)
source("./variableSettings.R")
#fileNamePrefix="preFiltOsc2x_"
if(filterData){
  fileNamePrefix<-filterPrefix
}

fileList<-read.table(paste0(outPath,"/fastqList.txt"),stringsAsFactors=F,header=T)

# extract the strain variable
strain<-factor(as.character(unique(fileList$sampleName),levels=c("366","382","775","784")))
SMC<-strain
levels(SMC)<-c("wt","dpy26cs","kle2cs","scc1cs")

controlGrp<-levels(SMC)[1] # control group
groupsOI<-levels(SMC)[-1]

```

# Wormcat category 1 - `r paste0("p",padjVal," lfc",lfcVal)`
```{r wormcat cat1, echo=F}
for(grp in groupsOI){
  grpPathUp=paste0(outPath,"/wormcat/",fileNamePrefix,grp,"_up/rgs_fisher_cat1_apv.svg")
  if(file.exists(grpPathUp)){
    fig_svg<-cowplot::ggdraw() + cowplot::draw_image(grpPathUp)
    plot(fig_svg)
    print("\n")
  }
  
  grpPathDown=paste0(outPath,"/wormcat/",fileNamePrefix,grp,"_down/rgs_fisher_cat1_apv.svg")
  if(file.exists(grpPathDown)){
    fig_svg<-cowplot::ggdraw() + cowplot::draw_image(grpPathDown)
    plot(fig_svg)
    print("\n")
  }
}
```


# Wormcat category 2 - `r paste0("p",padjVal," lfc",lfcVal)`

```{r wormcat cat2, echo=F, eval=T}
for(grp in groupsOI){
  grpPathUp=paste0(outPath,"/wormcat/",fileNamePrefix,grp,
                   "_up/rgs_fisher_cat2_apv.svg")
  if(file.exists(grpPathUp)){
    fig_svg<-cowplot::ggdraw() + cowplot::draw_image(grpPathUp)
    plot(fig_svg)
    print("\n")
  }
  
  grpPathDown=paste0(outPath,"/wormcat/",fileNamePrefix,grp,
                     "_down/rgs_fisher_cat2_apv.svg")
  if(file.exists(grpPathDown)){
    fig_svg<-cowplot::ggdraw() + cowplot::draw_image(grpPathDown)
    plot(fig_svg)
    print("\n")
  }
}
```

# Wormcat category 3 - `r paste0("p",padjVal," lfc",lfcVal)`

```{r wormcat cat3, echo=F, eval=T}
for(grp in groupsOI){
  grpPathUp=paste0(outPath,"/wormcat/",fileNamePrefix,grp,
                   "_up/rgs_fisher_cat3_apv.svg")
  if(file.exists(grpPathUp)){
    fig_svg<-cowplot::ggdraw() + cowplot::draw_image(grpPathUp)
    plot(fig_svg)
    print("\n")
  }
  
  grpPathDown=paste0(outPath,"/wormcat/",fileNamePrefix,grp,
                     "_down/rgs_fisher_cat3_apv.svg")
  if(file.exists(grpPathDown)){
    fig_svg<-cowplot::ggdraw() + cowplot::draw_image(grpPathDown)
    plot(fig_svg)
    print("\n")
  }
}
```
