---
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(cowplot)
library(magick)
source("variableSettings.R")
#fileNamePrefix="preFiltOsc2x_"
if(filterData){
  fileNamePrefix<-filterPrefix
}

fileList<-read.table(paste0(outPath,"/fastqList.txt"),stringsAsFactors=F,header=T)

# extract the strain variable
strain<-factor(as.character(unique(fileList$sampleName),levels=c("366","382","775","784")))
SMC<-strain
levels(SMC)<-c("wt","dpy26cs","kle2cs","scc1cs")

controlGrp<-levels(SMC)[1] # control group
groupsOI<-levels(SMC)[-1]
```

# GO enrichment - `r paste0("p",padjVal," lfc",lfcVal)`

```{r GOterm, echo=F}
for(grp in groupsOI){
  grpPathUp=paste0(getwd(),"/tissue/tea/",fileNamePrefix,grp,"_up_go.svg")
  if(file.exists(grpPathUp)){
    fig_svg<-cowplot::ggdraw() + cowplot::draw_image(grpPathUp) + 
      cowplot::draw_label(paste0(grp," up"), colour = "#80404080",
                          x=1,y=0.1,vjust=0,hjust=1)
    plot(fig_svg)
  }
  
  grpPathDown=paste0(getwd(),"/tissue/tea/",fileNamePrefix,grp,"_down_go.svg")
  if(file.exists(grpPathDown)){
    fig_svg<-cowplot::ggdraw() + cowplot::draw_image(grpPathDown) + 
      cowplot::draw_label(paste0(grp," down"), colour = "#80404080",
                          x=1,y=0.1,vjust=0,hjust=1)
    plot(fig_svg)
  }
}
```


# Tissue enrichment - `r paste0("p",padjVal," lfc",lfcVal)`

```{r tissue, echo=F}
for(grp in groupsOI){
  grpPathUp=paste0(getwd(),"/tissue/tea/",fileNamePrefix,grp,"_up_tissue.svg")
  if(file.exists(grpPathUp)){
    fig_svg<-cowplot::ggdraw() + cowplot::draw_image(grpPathUp) +
      cowplot::draw_label(paste0(grp," up"), colour = "#80404080",
                          x=1,y=0.1,vjust=0,hjust=1)
    plot(fig_svg)
  }
  
  grpPathDown=paste0(getwd(),"/tissue/tea/",fileNamePrefix,grp,"_down_tissue.svg")
  if(file.exists(grpPathDown)){
    fig_svg<-cowplot::ggdraw() + cowplot::draw_image(grpPathDown) +
      cowplot::draw_label(paste0(grp," down"), colour = "#80404080",
                          x=1,y=0.1,vjust=0,hjust=1)
    plot(fig_svg)
  }
}
```


# Phenotype enrichment - `r paste0("p",padjVal," lfc",lfcVal)`

```{r phenotype, echo=F}
for(grp in groupsOI){
  grpPathUp=paste0(getwd(),"/tissue/tea/",fileNamePrefix,grp,"_up_phe.svg")
  if(file.exists(grpPathUp)){
    fig_svg<-cowplot::ggdraw() + cowplot::draw_image(grpPathUp) + 
      cowplot::draw_label(paste0(grp," up"), colour = "#80404080",
                          x=1,y=0.1,vjust=0,hjust=1)
    plot(fig_svg)
  }
  
  grpPathDown=paste0(getwd(),"/tissue/tea/",fileNamePrefix,grp,"_down_phe.svg")
  if(file.exists(grpPathDown)){
    fig_svg<-cowplot::ggdraw() + cowplot::draw_image(grpPathDown) + 
      cowplot::draw_label(paste0(grp," down"), colour = "#80404080",
                          x=1,y=0.1,vjust=0,hjust=1)
    plot(fig_svg)
  }
}
```
